### ISSUE TITLE
Error: "Can not handle type of"  when code runs the "findNearest" function

### ISSUE THREAD

**Issue by cujoisa** [bertis-informatics/deep-mrm#1]
Hi, Thanks for the code upload. I'm running this in conda, and keep running into this issue with reading in the mz values and the tolerance values. What were the configurations used to convert your raw files to mzML?

[11-13-2023 10:35:24] [   INFO] [DeepMRM] Arguments: Namespace(target='./data/PID83_Transitions_DeepMRM.csv', input='./data/mpe230203_OE480_PID83_Forward_Std08_25fmol_R1.mzML', tolerance=10)
[11-13-2023 10:35:24] [   INFO] [DeepMRM] Load transition file from: /home/cujoisa/deep-mrm/data/PID83_Transitions_DeepMRM.csv
[11-13-2023 10:35:24] [   INFO] [DeepMRM] Load mass-spec file from: /home/cujoisa/deep-mrm/data/mpe230203_OE480_PID83_Forward_Std08_25fmol_R1.mzML
[11-13-2023 10:35:24] [   INFO] [DeepMRM] Load total 733 target peptides
[11-13-2023 10:35:24] [   INFO] [DeepMRM] load model from /home/cujoisa/deep-mrm/models/DeepMRM_BD.pth
[11-13-2023 10:35:24] [   INFO] [DeepMRM] load model from /home/cujoisa/deep-mrm/models/DeepMRM_QS.pth
[11-13-2023 10:35:44] [   INFO] [DeepMRM] Mass-spec data contains 2 chromatograms and 81311 spectra
[11-13-2023 10:35:44] [   INFO] [DeepMRM] Start extracting chromatograms for targeted peptides
  1%|▉                                                                                                                                                                 | 454/81311 [00:00<02:41, 500.49it/s]
Traceback (most recent call last):
  File "/home/cujoisa/deep-mrm/deepmrm/predict/make_prediction.py", line 61, in <module>
    result_dict = run_deepmrm_with_mzml(
  File "/home/cujoisa/deep-mrm/deepmrm/predict/interface.py", line 150, in run_deepmrm_with_mzml
    ds.extract_data(tolerance=tolerance)
  File "/home/cujoisa/deep-mrm/deepmrm/data/dataset/prm.py", line 57, in extract_data
    prod_peak = spectrum.find_peak_with_tolerance(prod_mz, tolerance)
  File "/home/cujoisa/deep-mrm/mstorch/data/mass_spec/spectrum.py", line 66, in find_peak_with_tolerance
    index = self.ms_spec.findNearest(mz, tolerance.get_mz_tolerance(mz))
  File "pyopenms/pyopenms_1.pyx", line 5272, in pyopenms.pyopenms_1.MSSpectrum.findNearest
Exception: can not handle type of (1320.667391, 10)

**Comment by cujoisa** [comment]
Update: we tried it with one of the LINCS raw files used in the paper and still getting the same error: F20131112_LINCS_MCF7-Rep1-16_DMSO_01.raw

**Comment by Jungkap** [comment]
Hi Chinmaya,

Thanks for your interest in DeepMRM. The error message comes out of
pyOpenMS library which is used to read mzML files.
If you are running it in the Conda environment, can you check the version
of pyOpenMS installed in your conda environment? DeepMRM requires pyOpenMS
v2.7. If you have installed previous or recent version, please uninstall it
and reinstall v2.7.

To simply avoid these issues, I recommend you to run DeepMRM with docker:
https://github.com/bertis-informatics/deep-mrm#docker-1

Let me know if you have any other issues.

Thanks
Jungkap
